name: Build, Test, Publish

on:
  push:
    branches:
      - main

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build, lint, and publish
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install api-extractor
        run: npm i -g api-extractor

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.PAT }}

      - name: Build code
        run: node common/scripts/install-run-rush.js build
      
      - name: Lint code
        run: cd packages/tscgen && npm run lint

      - name: Test code
        run: cd packages/tscgen && npm run test

      - name: Publish package
        run: cd packages/tscgen && npm run changeset:publish
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
